name: dimengen
description: "Flutter Dimensions Generator (it helps you centralize spacing and size values, improve UI consistency, and boost code readability and maintainability)"
version: 1.0.0
homepage: "https://github.com/warioddly/dimengen"

environment:
  sdk: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  source_gen: ^4.0.2
  build: ^4.0.2
  analyzer: 8.2.0

dev_dependencies:
  flutter_lints: ^6.0.0
  build_runner: ^2.10.3

topics:
  - dimensions
  - generator
  - sizes
  - uikit
  - gen

platforms:
  linux:
  macos:
  windows:
